server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true